# Generated by Django 3.2.16 on 2025-04-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20250422_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Publication', 'verbose_name_plural': 'Publication'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck the box to hide the post.', verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Page ID for URL; Latin characters, numbers,hyphens and underscores are allowed.', unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck the box to hide the post.', verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck the box to hide the post.', verbose_name='Published'),
        ),
    ]
